### PR TITLE
Adding HTTPS support

### PR DESCRIPTION
**Pull request by VeridianDynamics**

### CODE REVIEW

**Comment by ralscha** [comment]
Hi

Thanks for the pull request. I merged it and the snapshot release is now available from the sonatype repository


```
     		<dependency>
			<groupId>ch.rasc</groupId>
			<artifactId>embeddedtc</artifactId>
			<version>1.17-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
```

```
	<repositories>
		<repository>
			<id>sonatype</id>
			<name>sonatype</name>
			<url>https://oss.sonatype.org/content/groups/public</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<enabled>true</enabled>
			</releases>
		</repository>
	</repositories>
```

**Comment by ralscha** [comment]
I also added your changes to the Tomcat8 branch

```
<dependency>
      <groupId>ch.rasc</groupId>
            <artifactId>embeddedtc</artifactId>
            <version>2.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by VeridianDynamics** [comment]
Thank you, do you have an ETA on when it will be available in the release repository?

**Comment by ralscha** [comment]
It's not released yet. But I can start the process in about one hour. Does
everything work as expected?

**Comment by VeridianDynamics** [comment]
It's not _that_ urgent, but for me, everything works as it should. Thanks.

**Comment by ralscha** [comment]
I released 1.17 (Tomcat 7) and 2.0 (Tomcat 8). 
Should be available from the central maven repository shortly.
Thanks again for the contribution.

**Pull request merged**
